### ISSUE TITLE
Integration with souffle-lint?

### ISSUE THREAD

**Issue by langston-barrett** [jdaridis/souffle-lsp-plugin#2]
I'm not very familiar with LSP, so I don't know if language servers usually integrate with linters - but I think it would be nice to have the little editor squiggles for [`souffle-lint`](https://github.com/langston-barrett/souffle-lint#rule-categories) lints! Perhaps the LSP server could execute `souffle-lint` if it's on the `$PATH`, and `souffle-lint` could print source spans and messages as JSON that the LSP server could consume? Maybe something like:
```json
{ 
  "begin": {"line": 1, "col": 1}
  "end": {"line": 2, "col": 12}
  "message": "Redundant fact [...]"
}
```
What do you think?

**Comment by jdaridis** [comment]
Unfortunately, the editor squiggles indicating errors/warnings are tightly integrated with the original grammar/parser. When there is a parse error the server notifies the client about it. To send the error notification I need the file, line and column start and end, which I get from the parser.

I will try, though, to see what can be changed/added in order to integrate the linter, but I can't promise it is gonna play nicely

**Comment by langston-barrett** [comment]
I've [added support](https://github.com/langston-barrett/souffle-lint/pull/68) for JSON output to `souffle-lint`.
The output looks like this:
```json
{
  "fragments": [
    {
      "node_text": "SrcVal bshr Imm",
      "start": {
        "row": 5673,
        "column": 26
      },
      "end": {
        "row": 5673,
        "column": 41
      },
      "context": {
        "node_text": "Val = SrcVal bshr Imm",
        "start": {
          "row": 5673,
          "column": 20
        },
        "end": {
          "row": 5673,
          "column": 41
        },
        "context": null
      }
    }
  ],
  "rule": {
    "name": "style-symb-op",
    "short": "Prefer symbolic operators",
    "long": null,
    "captures": false,
    "slow": false,
    "queries": [ ... ],
    "examples": [
      {
        "before": "rule(x band y) :- rule(x), rule(y).\n",
        "after": "rule(x & y) :- rule(x), rule(y).\n"
      },
      {
        "before": "rule(lnot y) :- rule(y).\n",
        "after": "rule(!y) :- rule(y).\n"
      }
    ]
  },
  "source": "",
  "source_file": "bench/ddisasm.dl"
}
```
The "fragments" are the bits of the source file that the rule finds to be problematic. These come with "context", which are their parents in the syntax tree. The "rule" is the "lint". It comes with examples and a bit of metadata.
I've [added support](https://github.com/langston-barrett/souffle-lint/pull/68) for JSON output to `souffle-lint`.
The output looks like this:
```json
{
  "fragments": [
    {
      "node_text": "SrcVal bshr Imm",
      "start": {
        "row": 5673,
        "column": 26
      },
      "end": {
        "row": 5673,
        "column": 41
      },
      "context": {
        "node_text": "Val = SrcVal bshr Imm",
        "start": {
          "row": 5673,
          "column": 20
        },
        "end": {
          "row": 5673,
          "column": 41
        },
        "context": null
      }
    }
  ],
  "rule": {
    "name": "style-symb-op",
    "short": "Prefer symbolic operators",
    "long": null,
    "captures": false,
    "slow": false,
    "queries": [ ... ],
    "examples": [
      {
        "before": "rule(x band y) :- rule(x), rule(y).\n",
        "after": "rule(x & y) :- rule(x), rule(y).\n"
      },
      {
        "before": "rule(lnot y) :- rule(y).\n",
        "after": "rule(!y) :- rule(y).\n"
      }
    ]
  },
  "source": "",
  "source_file": "bench/ddisasm.dl"
}
```
The "fragments" are the bits of the source file that the rule finds to be problematic. These come with "context", which are their parents in the syntax tree. The "rule" is the "lint". It comes with examples and a bit of metadata.

I'll create a new release soon with this feature.

**Comment by langston-barrett** [comment]
[v0.4.0 of souffle-lint](https://github.com/langston-barrett/souffle-lint/releases/tag/v0.4.0) has support for JSON output. Try it out with:
```bash
souffle-lint lint --format json prog.dl
```

**Comment by jdaridis** [comment]
Added integration with [souffle-lint](https://github.com/langston-barrett/souffle-lint) with source code action. 
![souffle-lint](https://user-images.githubusercontent.com/46219992/201532576-e0083a95-7a42-48ef-8bdf-0ce3148f10c6.png)
![Screenshot from 2022-11-13 18-24-29](https://user-images.githubusercontent.com/46219992/201532553-4de05835-ee1c-4c2e-bd36-00034df85bdd.png)

**Comment by langston-barrett** [comment]
@jdaridis That looks great!! :-) Thanks for collaborating with me on this.

**Comment by jdaridis** [comment]
My pleasure. I think this addition unlocks many possibilities
